# This file was generated by GoReleaser. DO NOT EDIT.
class Ccf < Formula
  desc "Companion tool for ouchan/linkbatchd."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.24"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.24/ouchantools_1.0.24_darwin_amd64.tar.gz"
    sha256 "1d62871a26b1b1324edf3fb71c893888b3947e498a1f3073c71201f40511d8eb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.24/ouchantools_1.0.24_linux_amd64.tar.gz"
      sha256 "2c552465975ef98ca0ab674cea39ad7a2693c58125790f78864cc2f1b5b26d80"
    end
  end

  def install
    bin.install "ccf"
  end

  test do
    assert_match /Collection of internal commands/, shell_output("#{bin}/ccf -h", 0)
  end
end
